### PR TITLE
First version of nuget package scripts for evaluation.

### PR DESCRIPTION
**Pull request by ghost**
As discussed on Allegro mailing lists. See the `Readme-NuGet.markdown` file.

**I don't recommend merging this as it is**

I would welcome some discussion on:
1. Is the UI stuff useful (at the moment you can pick which addons to use, could also in the future select static/dynamic or debug/non-debug)
2. At the moment it uses the dynamic link libraries, would it better to use statics
3. Anything else!

### CODE REVIEW

**Comment by SiegeLord** [comment]
I haven't tried using this yet... is the UI invoked when you try to use the package in MSVC?

Do you think we should have a different package for static vs dynamic libraries?

**Comment by ghost** [comment]
The UI appears on the Project Properties Page (see attachment). It's not amazingly useful, the main benefit is to copy the correct set of DLLs into the exe's directory on build.
property page
There could be a different package for static/dynamic or the UI could be expanded to include that option. The down-side is that if the package includes all combinations of all libraries it will get big. I'd be in favor of focusing on static linking. (by the way do you mean static link just Allegro or libraries such as libpng, zlib etc as well?)
Also I realise this pull is against a version of allegro_winpkg which is not current. If my git skills are sufficient I will re-submit it against the latest.

**Comment by SiegeLord** [comment]
Ah, that's cool. Yes, that seems useful enough.

For the types of libraries, I've resigned to always statically link the dependencies, but still have the option for dynamic linking for Allegro. Thus, in practice, you'll have the choice of static vs dynamic vs dynamic debug linking for Allegro itself (in addition to the monolith variants of the above two).

And yes, I'd appreciate it if you rebased over the current codebase, as none of the dependency dlls are generated anymore.

**Comment by SiegeLord** [comment]
Another thing that occurs to me is that if we package the dependencies separately, it'd simplify the AppVeyor CI script we have now.

**Comment by ghost** [comment]
My git skills were not sufficient. I ended up with a weird branch with some commits in twice. I'll redo it from the start, hopefully this weekend.
To summarise, we want 2 options:
- Allegro static and dependencies static
- Allegro dynamic and dependencies static

Right? Sorry it's taking so long.

**Comment by SiegeLord** [comment]
No worries, I really appreciate your work with this. Yes, those two options sound like what we want.

**Pull request closed without merging**
