### PR TITLE
Nuget package 2

### PR DESCRIPTION
**Pull request by ghost**
Second try at this. It creates 2 packages, one for the deps and one for allegro itself (so you can use the former for Appveyor, maybe)
It creates 32 and 64 bit libraries with dependencies static and allegro static or dynamic depending on user choice (in the VS gui)

### CODE REVIEW

**Comment by SiegeLord** [comment]
Sorry, I've been super busy with things and didn't have the brain power to go through this. I'll test this ASAP. It looks awesome at a glance though!

**Comment by SiegeLord** [comment]
I tried this today but got an error building libpng:

```
***** Building Dependency libpng-1.6.17 *****
-- Building for: Visual Studio 14 2015
-- The C compiler identification is MSVC 19.0.23026.0
-- Check for working C compiler using: Visual Studio 14 2015
-- Check for working C compiler using: Visual Studio 14 2015 -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Found ZLIB: C:/dev/allegro_winpkg/universal/nupkg/64/lib/zlib.lib (found vers
ion "1.2.8")
-- Configuring done
-- Generating done
-- Build files have been written to: C:/dev/allegro_winpkg/universal/nupkg/64/li
bpng-1.6.17
Microsoft (R) Build Engine version 14.0.23107.0
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 12/7/2015 10:32:30 PM.
Project "C:\dev\allegro_winpkg\universal\nupkg\64\libpng-1.6.17\INSTALL.vcxproj
" on node 1 (default targets).
Project "C:\dev\allegro_winpkg\universal\nupkg\64\libpng-1.6.17\INSTALL.vcxproj
" (1) is building "C:\dev\allegro_winpkg\universal\nupkg\64\libpng-1.6.17\ALL_B
UILD.vcxproj" (2) on node 1 (default targets).
Project "C:\dev\allegro_winpkg\universal\nupkg\64\libpng-1.6.17\ALL_BUILD.vcxpr
oj" (2) is building "C:\dev\allegro_winpkg\universal\nupkg\64\libpng-1.6.17\ZER
O_CHECK.vcxproj" (3) on node 1 (default targets).
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.Cpp.Platform.t
argets(55,5): error MSB8020: The build tools for Visual Studio 2010 (Platform T
oolset = 'v100') cannot be found. To build using the v100 build tools, please i
nstall Visual Studio 2010 build tools.  Alternatively, you may upgrade to the c
urrent Visual Studio tools by selecting the Project menu or right-click the sol
ution, and then selecting "Retarget solution". [C:\dev\allegro_winpkg\universal
\nupkg\64\libpng-1.6.17\ZERO_CHECK.vcxproj]
Done Building Project "C:\dev\allegro_winpkg\universal\nupkg\64\libpng-1.6.17\Z
ERO_CHECK.vcxproj" (default targets) -- FAILED.

Done Building Project "C:\dev\allegro_winpkg\universal\nupkg\64\libpng-1.6.17\A
LL_BUILD.vcxproj" (default targets) -- FAILED.

Done Building Project "C:\dev\allegro_winpkg\universal\nupkg\64\libpng-1.6.17\I
NSTALL.vcxproj" (default targets) -- FAILED.


Build FAILED.

"C:\dev\allegro_winpkg\universal\nupkg\64\libpng-1.6.17\INSTALL.vcxproj" (defau
lt target) (1) ->
"C:\dev\allegro_winpkg\universal\nupkg\64\libpng-1.6.17\ALL_BUILD.vcxproj" (def
ault target) (2) ->
"C:\dev\allegro_winpkg\universal\nupkg\64\libpng-1.6.17\ZERO_CHECK.vcxproj" (de
fault target) (3) ->
(PlatformPrepareForBuild target) ->
  C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.Cpp.Platform
.targets(55,5): error MSB8020: The build tools for Visual Studio 2010 (Platform
 Toolset = 'v100') cannot be found. To build using the v100 build tools, please
 install Visual Studio 2010 build tools.  Alternatively, you may upgrade to the
 current Visual Studio tools by selecting the Project menu or right-click the s
olution, and then selecting "Retarget solution". [C:\dev\allegro_winpkg\univers
al\nupkg\64\libpng-1.6.17\ZERO_CHECK.vcxproj]

    0 Warning(s)
    1 Error(s)
```

It otherwise builds fine with build_deps_msvc2015_64.bat. Any ideas what you could be doing differently? I looked a the script, but I saw nothing special...

**Comment by ghost** [comment]
Don't know; it seems like CMake has picked the wrong toolset for libpng.
I've never seen that and I don't have VS 2010 tools installed. Will look
into it.

**Comment by ghost** [comment]
Can you just check the setting for <PlatformToolset> in `ZERO_CHECK.vcxproj` in libpng's build directory? Should be 'v140' not 'v100'.

**Comment by SiegeLord** [comment]
Alright, I managed to resolve the issue. Turns out, the png build script wasn't generating the RelWithDebInfo configuration. After that was fixed, everything worked out.

There are a few small things I will tweak at a later point. One big issue is that the internet suggests that it's not possible to mix and match 32 and 64 bit binaries in a single package, so I may have to split them. Also, I'm not completely sure about what to do with respect to the MSVC version. It seems 2015 has the best nuget support, but what happens when the 201x version is released? Do we need a package per version? I'm still exploring the best thing to do here.

Anyway, all those things are small tweaks compared to what has already been done by you. I really appreciate this work! It will be truly is dead simple to install Allegro once we're finished with this.

**Comment by SiegeLord** [comment]
Nevermind, of course a package can contain multiple binary versions, I just misunderstood the errors I've been getting. Supporting 2015 and 2012 and etc is easy too, just add another layer of directories. I'll try doing that sometime soon.

**Comment by ghost** [comment]
Thanks SL. I hope the process of listing the files in the .nuspec and referring to them in the MSBuild fragment is now self-evident (took _me_ ages to get my head around it!) I know that changes in VS2015 broke other libraries (e.g. [gamedev.net](http://www.gamedev.net/topic/664434-problem-installing-sdl-in-visual-studio-2015/), [stackoverflow](http://stackoverflow.com/questions/30412951/unresolved-external-symbol-imp-fprintf-and-imp-iob-func-sdl2), ...) so we may have to plan to refresh the package every time MS brings out a new version.

**Pull request merged**
